name: hnh_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  json_serializable: ^6.3.1
  retrofit: ^3.0.1+1

  logger: any  #for logging purpose
  splash_screen_view: any
  google_maps_flutter: ^2.0.6
  permission_handler: ^10.0.0
  location_permissions: ^4.0.1
  path_provider: ^2.0.8
  progress_dialog: ^1.2.4
  shared_preferences: any
  flutter_svg: any
  provider: any
  intl: any
  percent_indicator: ^4.2.2
  table_calendar: ^2.3.3
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  overlay_support: ^2.0.1
  flutter_local_notifications: ^9.5.3+1
  get: ^4.6.5
  flutter_bloc: ^8.0.1
  connectivity_plus: ^2.3.6
  animated_button_bar: ^0.0.2+1
  fl_chart: ^0.55.1
  syncfusion_flutter_charts: ^20.2.43
  image_picker: ^0.8.5+3
  flutter_slidable: any
  barcode_scan2: ^4.2.1
  fbroadcast: ^2.0.0
  visibility_detector: ^0.3.3
  firebase_remote_config: ^2.0.17
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.5
  carousel_slider: ^4.0.0
  local_auth: ^2.1.2
  camera: ^0.10.0+3
  line_icons: ^2.0.1
  cached_network_image: ^3.2.2
  flutter_webrtc: ^0.9.11
  socket_io_client: ^2.0.0
  web_socket_channel: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  build_runner: ^2.0.6
  retrofit_generator: ^4.0.3+1



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf

splash_screen_view:
  color: "#ffffff"
  #background_image: "assets/splashscreen_image.png"
  # Optional parameters are listed below.
  #image: assets/icons/ic_launcher.png